name 'immutable'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures immutable'
long_description 'Installs/Configures immutable'
version '0.1.0'
