default[:immutable][:machine_type] = "processing"
default[:immutable][:ticket_number] = "ticket-number"
default[:immutable][:client] = "name of client" 
default[:immutable][:immutable_file] = "/etc/chef/machine.lock"
default[:immutable][:vault_info] = "pillar42"
default[:immutable][:se] = "se name"
